---
title:            "Fiona Abraham"
---





    EDUCATION	

APPALACHIAN STATE UNIVERSITY          						      
Boone, NC

Bachelor of Science in Business Administration

Computer Information Systems/Statistics Minor

December 2019

    RELEVANT COURSEWORK	
CIS 3250 – Systems Analysis & Design 
Focused on the strategies and technologies for building information systems in organizations.
Learned basic planning and discovery techniques as well as joint application development (JAD), information systems modeling, CASE technologies

CIS 3580 - Network & IT Infrastructures 
Introduced to the processes of selecting, modeling, configuring, and maintaining the components of an IT infrastructure. 
Examined current hardware components, networking devices, and security issues will be examined through both individual and group projects 


CIS 3680 - Programming Software Solutions 
- Utilization of Python programming language 

CIS 3750 - Database Management 
- Utilization of Oracle and MySQL

    PROFESSIONAL EXPERIENCE	
*APPALACHIAN STATE UNIVERSITY – OFFICE OF STUDENT AFFAIRS                        
Boone, NC

Accounting & Finance Assistant	
January 2018 – May 2018
					            
-Prepared budget and budget modification entries, journal entries, expenditure adjustments, deposits, and invoices

-Scanned and filed transactions in Fortis

-Performed bookkeeping entries in QuickBooks

-Prepared P-card Reconciliations/Direct Pay transactions with Accounts Payable processing

-Made deliveries and pick-ups in other departments as needed

    *OFFICE OF THE GOVERNOR – STATE OF NORTH CAROLINA                                                          
Intern –Pat McCrory for Governor                                                                                                        

May 2016 – November 2016

-Gathered data regarding whether or not registered Republicans planned on voting in the 2016 elections

    KUMON							                   			                                
English & Mathematics tutor 			 			                                            
March 2014 – May 2016
Cary, NC            

- Tutored students in grades K-10 on a variety of English and math topics in order to ensure clarity on topics 

- Provided proctoring services to students with hopes of proceeding to advanced topics 

- Recorded inventory from time-to-time when supervisors needed assistance

                                    
                                    



